# Generated by Django 3.2.6 on 2022-04-10 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserHabitsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Routine', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('date', models.TimeField(blank=True, default='20:08', null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='habits.userhabitsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='HabitsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 10, 20, 8, 8, 396295, tzinfo=utc), null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.title')),
            ],
        ),
    ]
