# Generated by Django 3.2.6 on 2022-04-10 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 10, 20, 12, 22, 623014, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.TimeField(blank=True, default='20:12', null=True),
        ),
    ]
