# Generated by Django 3.2.6 on 2022-04-11 02:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 11, 2, 0, 4, 933875, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.TimeField(blank=True, default='02:00', null=True),
        ),
    ]
